build:
  environment:
    php:
      version: 7.3

  tests:
    override:
      - php-scrutinizer-run
      -
        use_website_config: false
        command: vendor/bin/phpunit --coverage-clover clover.xml
        coverage:
          file: coverage.clover
          format: php-clover
