language: php
os: linux

env:
  - MYSQL_HOST=127.0.0.1 MYSQL_USER=root

php:
  - 7.3
  - 7.4
  - nightly

services:
  - mysql

matrix:
  allow_failures:
    - php: 7.4
    - php: nightly
  fast_finish: true

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS cert_manager;"

install:
  - "composer install"

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml
